site_name: help.envs.net
site_description: envs.net | help
repo_name: <i class="fa fa-github" aria-hidden="true"></i> edit on gitea
repo_url: https://git.envs.net/envs/help

theme: cyborg

nav:
- home: index.md
- faq: faq.md
- basic help: help.md
- user guide:
    - email: mail.md
    - website: website.md
    - blog: blog.md
    - database: database.md
    - gopher: gopher.md
    - gemini: gemini.md
    - finger: finger.md
- tutorials:
    - learn git:
        - home: tutorials/learngit/docs/README.md
        - glossary: tutorials/learngit/docs/glossary.md
        - common commands: tutorials/learngit/docs/common_commands.md
        - branching strategies: tutorials/learngit/docs/branching_strategies.md
        - troubleshooting: tutorials/learngit/docs/troubleshooting.md
        - ssh setup: tutorials/learngit/docs/ssh_setup.md
